@startuml
title Activity Diagram - Change Password

start

:User opens "Change Password" menu;
:User enters old password and new password;

if (Old password correct?) then (yes)
  :Update password with new value;
  :Update modification date;
  :Display confirmation message;
else (no)
  :Display error message "Incorrect old password";
  :Return to Change Password form;
endif

stop
@enduml
